service: aws-nodejs-example

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  timeout: 10
  stage: dev
  region: ap-southeast-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:*'
          Resource:
            - 'arn:aws:dynamodb:*:*'

functions:
  - ${file(./functions/functions.yml)}

resources:
  Resources:
    ${file(./resources/dynamodb.yml)}

custom:
  dynamodb:
    stages:
      - dev
    start:
      inMemory: true
      migrate: true

plugins:
  - serverless-dynamodb-local
  - serverless-offline