service: aws-nodejs-example

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  timeout: 10
  stage: dev
  region: ap-southeast-2

functions:
  - ${file(./functions/functions.yml)}

plugins:
  - serverless-offline